name: Laravel CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      # 3. Copy env
      - name: Copy .env
        run: cp .env.example .env

      # 4. Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      # 5. Generate key
      - name: Generate app key
        run: php artisan key:generate

      # 6. Set permissions
      - name: Set permissions
        run: chmod -R 777 storage bootstrap/cache

      # 7. Run tests
      - name: Run tests
        run: php artisan test
